### ISSUE TITLE
Can't upload translations to transifex

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#174]
```
(master cbe80fd) p@m /workspace/ckeditor5> gulp translations:upload
[10:28:31] Using gulpfile /workspace/ckeditor5/gulpfile.js
[10:28:31] Starting 'translations:upload'...
? Provide the Transifex token (generate it here: https://www.transifex.com/user/settings/api/): ******************************************
[10:28:33] Error: Status code: 400
[10:28:33] 'translations:upload' errored after 1.74 s
[10:28:33] Error: Status code: 400
    at Request.handleJsonResponse [as _callback] (/workspace/ckeditor5-dev/packages/ckeditor5-dev-env/lib/translations/transifex-service.js:109:19)
    at Request.self.callback (/workspace/ckeditor5-dev/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/workspace/ckeditor5-dev/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/workspace/ckeditor5-dev/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

Something... broke. Not sure what, though.

**Comment by ma2ciek** [comment]
Hmm. I found the bug, which I created during the translation tests coverage and refactoring.
According to the [docs](https://docs.transifex.com/api/resources) I changed the type of the [content](https://github.com/ckeditor/ckeditor5-dev/blob/6e04aa9bd43a48579b16e2a36074dbcbd97a2301/packages/ckeditor5-dev-env/lib/translations/upload.js#L55) variable from the ReadStream to the string as this should be the final type. So probably the `request` package does something more under the hood with converting the ReadStream before sending data which I don't understand for now. I'll create a ticket for it as the tests are much more complicated with the Stream usage, meanwhile I'll revert the working version.
