### ISSUE TITLE
The changelog generator crashes on non-existen CHANGELOG.md

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#187]
```
[23:14:44] Changelog for "@ckeditor/ckeditor5-undo" (v0.8.1) has been generated.
[23:14:44] 'changelog:dependencies' errored after 41 min
[23:14:44] TypeError: Cannot read property 'match' of null
    at Object.getLastFromChangelog (/workspace/ckeditor5-dev/packages/ckeditor5-dev-env/lib/release-tools/utils/versions.js:22:28)
    at generateChangelogForSinglePackage (/workspace/ckeditor5-dev/packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsinglepackage.js:33:29)
    at generateChangelogTask (/workspace/ckeditor5-dev/packages/ckeditor5-dev-env/lib/release-tools/tasks/generatechangelogforsubrepositories.js:50:10)
    at promise.then (/workspace/ckeditor5-dev/packages/ckeditor5-dev-env/lib/release-tools/utils/executeonpackages.js:22:33)
    at process._tickCallback (internal/process/next_tick.js:103:7)
(master 7fc0bf8) p@m /workspace/ckeditor5>
```

**Comment by pomek** [comment]
I must receive some debug data because I am not able to reproduce this bug.

I also cannot confirm this bug - please see [an integration test](https://github.com/ckeditor/ckeditor5-dev/pull/180/files#diff-6a4849eb7bf3de35d424f978a9bc01a6R50) which has been introduced in #180.

**Comment by Reinmar** [comment]
Isn't this stack trace enough? I'm looking in the code now and where's the condition that `CHANGELOG.md` does not exist handled in `getLastFromChangelog()` in the version utils?

**Comment by Reinmar** [comment]
I can easily reproduce this by resetting some CKE5 package back to a place where we didn't have changelogs. E.g. ckeditor5-lists: `git reset --hard v0.5.0`.

**Comment by pomek** [comment]
Thx!
