### ISSUE TITLE
Building docs doesn't work on windows

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-dev#619]
1.  clone CKE5 repo
2.  execute `yarn` to install the deps
3.  execute `yarn run docs` to build the docs

Currently you can't build it, errors are being thrown. There's one minor issue in ckeditor5-dev but multiple other coming from umberto dependency.

**Comment by tomalec** [comment]
Here are my changes 
https://github.com/cksource/umberto/tree/docs-windows
https://github.com/ckeditor/ckeditor5-dev/tree/docs-windows
I get to the point where I get following warning:

<details>
<summary><pre><code>Building documentation failed: Error: Document: \index.md has no category id.
    at Hexo.<anonymous> (D:\repos\umberto\scripts\filter\before-post-render\validate-page-data.js:40:9)</code></pre></summary>
<pre><code>
$ node --inspect-brk --max-old-space-size=4096 ./scripts/docs/build-docs.js
Debugger listening on ws://127.0.0.1:9229/e40df85e-9cdc-4d23-8620-0c8d902384e2
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger attached.
JSDoc started...
No errors found during the validation.
Documented 568 files!
Clean build directory.
Emptying Hexo source directory.
Building API docs of CKEditor 5...
Built API docs in: 8:30.961 (m:ss.mmm)
Error: There was something wrong during hexo generation.
Building documentation failed: Error: Document: \index.md has no category id.
    at Hexo.<anonymous> (D:\repos\umberto\scripts\filter\before-post-render\validate-page-data.js:40:9)
    at Hexo.tryCatcher (D:\repos\umberto\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\repos\umberto\node_modules\bluebird\js\release\method.js:15:34)
    at D:\repos\umberto\node_modules\hexo\lib\extend\filter.js:60:50
    at tryCatcher (D:\repos\umberto\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (D:\repos\umberto\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (D:\repos\umberto\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (D:\repos\umberto\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\repos\umberto\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\repos\umberto\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\repos\umberto\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\repos\umberto\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\repos\umberto\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\repos\umberto\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\repos\umberto\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\repos\umberto\node_modules\bluebird\js\release\async.js:15:14)
(node:15152) UnhandledPromiseRejectionWarning: Error: Document: \index.md has no category id.
    at Hexo.<anonymous> (D:\repos\umberto\scripts\filter\before-post-render\validate-page-data.js:40:9)
    at Hexo.tryCatcher (D:\repos\umberto\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\repos\umberto\node_modules\bluebird\js\release\method.js:15:34)
    at D:\repos\umberto\node_modules\hexo\lib\extend\filter.js:60:50
    at tryCatcher (D:\repos\umberto\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (D:\repos\umberto\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (D:\repos\umberto\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (D:\repos\umberto\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\repos\umberto\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\repos\umberto\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\repos\umberto\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\repos\umberto\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\repos\umberto\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\repos\umberto\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\repos\umberto\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\repos\umberto\node_modules\bluebird\js\release\async.js:15:14)
(node:15152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Failed to import a guide from builds/guides/support/browser-compatibility in document: ckeditor5/18.0.0/framework/guides/support/browser-compatibility.md
Failed to import a guide from builds/guides/support/getting-support in document: ckeditor5/18.0.0/framework/guides/support/getting-support.md
Failed to import a guide from builds/guides/support/reporting-issues in document: ckeditor5/18.0.0/framework/guides/support/reporting-issues.md
Error: Failed while convert {@link features/ckfinder &#x201C;CKFinder integration&#x201D; guide} tag in ckeditor5/18.0.0/api/adapter-ckfinder.md.
Error: Failed while convert {@link features/image-upload comprehensive &#x201C;Image upload&#x201D; guide} tag in ckeditor5/18.0.0/api/adapter-ckfinder.md.
Error: Failed while convert {@link features/text-alignment#demo demo in the Text alignment feature} tag in ckeditor5/18.0.0/api/alignment.md.
Error: Failed while convert {@link features/text-alignment Text alignment feature} tag in ckeditor5/18.0.0/api/alignment.md.
Error: Failed while convert {@link features/autoformat Autoformat feature} tag in ckeditor5/18.0.0/api/autoformat.md.

...
</code></pre>
</details>

**Comment by pomek** [comment]
[Changes proposed by @tomalec in `ckeditor5-dev`](https://github.com/ckeditor/ckeditor5-dev/compare/docs-windows) are enough for Umberto. The rest of the task must be handled on Umberto side.
