### ISSUE TITLE
The `gulp docs` command throwing an error

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-dev#69]
The `gulp docs` task throws error:

```
/ckeditor5/node_modules/@ckeditor/jsdoc-plugins/lib/longname-fixer/fixers/fix-links.js:18
		if ( !doclet.memberof.includes( className ) ) {
		                     ^

TypeError: Cannot read property 'includes' of undefined

```

Quick debugging shows that comments like this are causing the trouble:
https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/markercollection.js#L14

This should not break docs building process, and if it's a wrong usage of such shorthand there should be some warning.

**Comment by Reinmar** [comment]
A better link for the future reference: https://github.com/ckeditor/ckeditor5-engine/blob/ac52ee52559ab2d95b72bcf8b71c783a32e1c257/src/model/markercollection.js#L14

**Comment by szymonkups** [comment]
...and there is also no module defined in this file.

**Comment by Reinmar** [comment]
Another issue now:

```
[14:24:07] /workspace/ckeditor5-dev/packages/jsdoc-plugins/lib/validator/doclet-validator.js:137
				.map( typeExpression => typeExpression.name || typeExpression.expression.name ) :
				                                                                        ^

TypeError: Cannot read property 'name' of undefined
    at Array.isArray.param.type.parsedType.elements.filter.map.typeExpression (/workspace/ckeditor5-dev/packages/jsdoc-plugins/lib/validator/doclet-validator.js:137:77)
    at Array.map (native)
    at DocletValidator._lintElementParams (/workspace/ckeditor5-dev/packages/jsdoc-plugins/lib/validator/doclet-validator.js:137:6)
    at DocletValidator._lintParams (/workspace/ckeditor5-dev/packages/jsdoc-plugins/lib/validator/doclet-validator.js:121:10)
    at DocletValidator.findErrors (/workspace/ckeditor5-dev/packages/jsdoc-plugins/lib/validator/doclet-validator.js:58:8)
    at parseComplete (/workspace/ckeditor5-dev/packages/jsdoc-plugins/lib/validator/validator.js:18:28)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Parser.parse (/workspace/ckeditor5-dev/packages/ckeditor5-dev-docs/node_modules/jsdoc/lib/jsdoc/src/parser.js:183:10)
    at Object.module.exports.cli.parseFiles (/workspace/ckeditor5-dev/packages/ckeditor5-dev-docs/node_modules/jsdoc/cli.js:356:42)
    at module.exports.cli.main (/workspace/ckeditor5-dev/packages/ckeditor5-dev-docs/node_modules/jsdoc/cli.js:226:14)
    at Object.module.exports.cli.runCommand (/workspace/ckeditor5-dev/packages/ckeditor5-dev-docs/node_modules/jsdoc/cli.js:180:5)
    at /workspace/ckeditor5-dev/packages/ckeditor5-dev-docs/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/workspace/ckeditor5-dev/packages/ckeditor5-dev-docs/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

[14:24:07] JSDoc returned with error code: 1
```

Somewhere on https://github.com/ckeditor/ckeditor5-typing/pull/71

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-dev/issues/89.
